name: Create or Update Release

on:
  push:
    tags:
      - 'v*' # Trigger hanya untuk tag yang diawali dengan 'v'

jobs:
  release:
    name: Create or Update Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Pastikan semua data git history diambil

      ## Step 2: Install GitHub CLI (gh)
      #- name: Install GitHub CLI
      #  run: sudo apt-get install -y gh

      # Step 3: Set GH_TOKEN environment variable
        # GH_TOKEN digunakan oleh GitHub CLI untuk autentikasi
      - name: Configure GitHub CLI token
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GitHub CLI configured."

      # Step 4: Periksa apakah release dengan tag sudah ada
      - name: Check if release exists
        id: check_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_EXISTS=$(gh release view ${{ github.ref_name }} --json id --jq '.id' || echo "")
          echo "RELEASE_EXISTS=$RELEASE_EXISTS" >> $GITHUB_ENV

      # Step 5: Buat release jika belum ada
      - name: Create release if not exists
        if: env.RELEASE_EXISTS == ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} build/${{ env.ZIP_NAME }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Auto-generated release for tag ${{ github.ref_name }}"

      # Step 6: Update module.prop
      - name: Update module.prop
        env:
          MODULE_PROP: "module.prop"
        run: |
          UPDATE_URL="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/update.json"
          COMMIT_HASH=$(git rev-parse --short HEAD)
          NEXT_VER_CODE=${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}

          # Set version
          echo "Set version"
          if grep -q "^version=" "$MODULE_PROP"; then
            # override
            sed -i "s|^version=.*|version=${{ github.ref_name }}|" "$MODULE_PROP"
          else
            # append
            echo "version=${{ github.ref_name }}" >> "$MODULE_PROP"
          fi

          # Set version code
          echo "Set version code"
          #VERSION_CODE=$(date +"%Y%m%d")
          VERSION_CODE=$NEXT_VER_CODE
          if grep -q "^versionCode=" "$MODULE_PROP"; then
            # override
            sed -i "s|^versionCode=.*|versionCode=$VERSION_CODE|" "$MODULE_PROP"
          else
            # append
            echo "versionCode=$VERSION_CODE" >> "$MODULE_PROP"
          fi

          # Periksa apakah `updateJson` ada
          echo "Set updateJson"
          if grep -q "^updateJson=" "$MODULE_PROP"; then
            # Override nilai updateJson
            sed -i "s|^updateJson=.*|updateJson=$UPDATE_URL|" "$MODULE_PROP"
            echo "updateJson di-override dengan nilai baru di $MODULE_PROP."
          else
            # Tambahkan `updateJson` jika belum ada
            echo "updateJson=$UPDATE_URL" >> "$MODULE_PROP"
            echo "updateJson ditambahkan ke $MODULE_PROP."
          fi

          echo "result:"
          cat $MODULE_PROP

      # Step 7: Buat file ZIP dengan mengecualikan `.github`
      - name: Create zip file
        run: |
          mkdir build
          ZIP_NAME="BoxForMagisk-WebUI-${{ github.ref_name }}.zip"
          # build with github head
          # git archive --format=zip --output="build/$ZIP_NAME" HEAD ':!/.github'

          # build manual
          zip -r "build/$ZIP_NAME" . \
            -x ".git/*" \
            -x ".github/*" \
            -x "update.json" \
            -x "CHANGELOG.md" \
            -x "build/*"

          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          echo "Build results"
          cat $MODULE_PROP
          ls -la build

      # Step 8: Tambahkan asset ke release yang ada
      - name: Upload asset to existing release
        if: env.RELEASE_EXISTS != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} build/${{ env.ZIP_NAME }} --clobber

      # Step 9: Create update.json file
      - name: Create update.json
        run: |
          # Mengambil informasi dari file ZIP
          ZIP_FILE=$(ls build/BoxForMagisk-WebUI-*.zip 2>/dev/null | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "Tidak ada file ZIP yang ditemukan di folder build."
            exit 1
          fi

          # extract data
          ZIP_CONTENT=$(unzip -p "$ZIP_FILE" module.prop || echo "")
          VERSION=$(echo "$ZIP_CONTENT" | grep '^version=' | cut -d '=' -f 2)
          VERSION_CODE=$(echo "$ZIP_CONTENT" | grep '^versionCode=' | cut -d '=' -f 2)
          DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ github.ref_name }}/${{ env.ZIP_NAME }}"

          if [ -z "$VERSION" ]; then
            VERSION="${{ github.ref_name }}"
          fi

          # update data
          UPDATE_JSON_FILE="update.json"
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" $UPDATE_JSON_FILE
          sed -i "s/\"versionCode\": \".*\"/\"versionCode\": \"$VERSION_CODE\"/" $UPDATE_JSON_FILE
          sed -i "s/\"zipUrl\": \".*\"/\"zipUrl\": \"$DLURL\"/" $UPDATE_JSON_FILE
          
          echo "Result:"
          cat $UPDATE_JSON_FILE

      # Step 9: Commit UPDATE
      - name: Commit and Push update
        run: |
          # Menyiapkan Git user
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions[bot]"

          # show files
          ls -la

          # Commit hanya file update.json
          git commit -am "${{ github.ref_name }}"

          # Push perubahan ke remote branch release
          git push origin main
